/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type WorkflowDefinition = {
  _id: string
  _type: 'workflow.definition'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  documentType?: string
  description?: string
  forwardOnly?: boolean
  roles?: Array<
    {
      _key: string
    } & WorkflowRole
  >
  stages?: Array<
    {
      _key: string
    } & WorkflowStage
  >
  offRamps?: Array<
    {
      _key: string
    } & WorkflowOffRamp
  >
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type WorkflowAssignment = {
  _type: 'workflow.assignment'
  assignmentType?: string
  userId?: string
}

export type WorkflowOffRamp = {
  _type: 'workflow.offRamp'
  label?: string
  slug?: Slug
  icon?: WorkflowLucideIcon
  tone?: 'caution' | 'critical'
  stageCriteria?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  enablePublishing?: boolean
  unpublishOnEntry?: boolean
  allowedRoles?: Array<string>
  enableNotifications?: boolean
  notifyUserTypes?: Array<string>
}

export type WorkflowLucideIcon = string

export type WorkflowStage = {
  _type: 'workflow.stage'
  label?: string
  slug?: Slug
  icon?: WorkflowLucideIcon
  color?: WorkflowColor
  stageCriteria?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  taskTemplates?: Array<
    {
      _key: string
    } & WorkflowTaskTemplate
  >
  enableCompletionGating?: boolean
  gatingOverrideRoles?: Array<string>
  enablePublishing?: boolean
  enableNotifications?: boolean
  notifyUserTypes?: Array<string>
}

export type WorkflowColor = {
  _type: 'workflow.color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type WorkflowTaskTemplate = {
  _type: 'workflow.taskTemplate'
  title?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  assigneeRole?: string
  dueInDays?: number
  required?: boolean
}

export type WorkflowRole = {
  _type: 'workflow.role'
  label?: string
  slug?: Slug
  description?: string
  projectRoles?: Array<string>
}

export type WorkflowSetStatus = {
  _type: 'workflow.setStatus'
  statusLabel?: string
  statusSlug?: string
  statusIcon?: string
  completedAt?: string
  completedBy?: WorkflowUser
  reason?: string
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type WorkflowUser = {
  _type: 'workflow.user'
  userId?: string
}

export type CoachingGuide = {
  _id: string
  _type: 'coachingGuide'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: string
  assignments?: Array<
    {
      _key: string
    } & WorkflowAssignment
  >
  title?: string
  category?:
    | 'answering'
    | 'behavioral'
    | 'skills'
    | 'workStyles'
    | 'grading'
    | 'feedback'
    | 'situations'
    | 'practice'
  jobZones?: Array<number>
  summary?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3'
    listItem?: 'bullet'
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  statuses?: Array<
    {
      _key: string
    } & WorkflowSetStatus
  >
  pendingTransitionReason?: string
}

export type OnetOccupationMetadataItem = {
  _type: 'onetOccupationMetadataItem'
  item?: string
  response?: string
  n?: number
  percent?: number
  dateUpdated?: string
}

export type OnetInterestReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetInterest'
}

export type OnetInterestAreaScore = {
  _type: 'onetInterestAreaScore'
  area?: OnetInterestReference
  name?: string
  score?: number
  displayRank?: number
}

export type OnetOccupationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetOccupation'
}

export type OnetRelatedOccupationItem = {
  _type: 'onetRelatedOccupationItem'
  occupation?: OnetOccupationReference
  relatednessTier?: 'Primary-Short' | 'Primary-Long' | 'Supplemental'
  relatedIndex?: number
}

export type OnetContentModelElementReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetContentModelElement'
}

export type OnetScaleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetScale'
}

export type OnetRatingCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetRatingCategory'
}

export type OnetRatingItem = {
  _type: 'onetRatingItem'
  domain?:
    | 'essentialSkills'
    | 'transferableSkills'
    | 'knowledge'
    | 'abilities'
    | 'workActivities'
    | 'education'
    | 'trainingExperience'
    | 'workContext'
  element?: OnetContentModelElementReference
  scale?: OnetScaleReference
  ratingCategory?: OnetRatingCategoryReference
  dataValue?: number
  n?: number
  standardError?: number
  lowerCiBound?: number
  upperCiBound?: number
  recommendSuppress?: 'Y' | 'N'
  notRelevant?: 'Y' | 'N'
  dateUpdated?: string
  domainSource?: string
}

export type OnetWorkStyleItem = {
  _type: 'onetWorkStyleItem'
  element?: OnetContentModelElementReference
  scale?: OnetScaleReference
  dataValue?: number
  dateUpdated?: string
  domainSource?: string
}

export type OnetSoftwareSkillItem = {
  _type: 'onetSoftwareSkillItem'
  workplaceExample?: string
  element?: OnetContentModelElementReference
  hotTechnology?: 'Y' | 'N'
  inDemand?: 'Y' | 'N'
}

export type OnetReportedTitleItem = {
  _type: 'onetReportedTitleItem'
  reportedJobTitle?: string
  shownInMyNextMove?: 'Y' | 'N'
}

export type OnetJobTitleItem = {
  _type: 'onetJobTitleItem'
  jobTitle?: string
  shortTitle?: string
  sources?: string
}

export type OnetEmergingTaskItem = {
  _type: 'onetEmergingTaskItem'
  task?: string
  category?: 'New' | 'Revision'
  originalTaskId?: number
  originalTask?: string
  dateUpdated?: string
  domainSource?: string
}

export type OnetTaskDwaItem = {
  _type: 'onetTaskDwaItem'
  dwa?: OnetContentModelElementReference
  dateUpdated?: string
  domainSource?: string
}

export type OnetTaskRatingItem = {
  _type: 'onetTaskRatingItem'
  scale?: OnetScaleReference
  ratingCategory?: OnetRatingCategoryReference
  dataValue?: number
  n?: number
  standardError?: number
  lowerCiBound?: number
  upperCiBound?: number
  recommendSuppress?: 'Y' | 'N'
  notRelevant?: 'Y' | 'N'
  dateUpdated?: string
  domainSource?: string
}

export type OnetTaskItem = {
  _type: 'onetTaskItem'
  taskId?: number
  task?: string
  taskType?: 'Core' | 'Supplemental'
  incumbentsResponding?: number
  dateUpdated?: string
  domainSource?: string
  ratings?: Array<
    {
      _key: string
    } & OnetTaskRatingItem
  >
  dwas?: Array<
    {
      _key: string
    } & OnetTaskDwaItem
  >
}

export type OnetJobZoneReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'onetJobZone'
}

export type OnetOccupation = {
  _id: string
  _type: 'onetOccupation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  onetsocCode?: string
  title?: string
  description?: string
  jobZone?: OnetJobZoneReference
  tasks?: Array<
    {
      _key: string
    } & OnetTaskItem
  >
  emergingTasks?: Array<
    {
      _key: string
    } & OnetEmergingTaskItem
  >
  jobTitles?: Array<
    {
      _key: string
    } & OnetJobTitleItem
  >
  reportedTitles?: Array<
    {
      _key: string
    } & OnetReportedTitleItem
  >
  softwareSkills?: Array<
    {
      _key: string
    } & OnetSoftwareSkillItem
  >
  workStyles?: Array<
    {
      _key: string
    } & OnetWorkStyleItem
  >
  ratings?: Array<
    {
      _key: string
    } & OnetRatingItem
  >
  relatedOccupations?: Array<
    {
      _key: string
    } & OnetRelatedOccupationItem
  >
  interestProfile?: {
    riasec?: {
      realistic?: number
      investigative?: number
      artistic?: number
      social?: number
      enterprising?: number
      conventional?: number
    }
    highPoints?: Array<string>
    areas?: Array<
      {
        _key: string
      } & OnetInterestAreaScore
    >
  }
  surveyMetadata?: Array<
    {
      _key: string
    } & OnetOccupationMetadataItem
  >
}

export type OnetSurveyItem = {
  _type: 'onetSurveyItem'
  surveyItemNumber?: string
  scale?: OnetScaleReference
}

export type OnetInterest = {
  _id: string
  _type: 'onetInterest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  element?: OnetContentModelElementReference
  elementId?: string
  name?: string
  kind?: 'careerType' | 'specificArea'
  code?: string
  description?: string
  careerTypes?: Array<
    {
      _key: string
    } & OnetInterestReference
  >
  keywords?: Array<{
    keyword?: string
    keywordType?: 'Action' | 'Object'
    _type: 'onetInterestKeyword'
    _key: string
  }>
  activities?: Array<string>
  illustrativeOccupations?: Array<
    {
      _key: string
    } & OnetOccupationReference
  >
}

export type OnetLevelScaleAnchor = {
  _id: string
  _type: 'onetLevelScaleAnchor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  element?: OnetContentModelElementReference
  scale?: OnetScaleReference
  anchorValue?: number
  anchorDescription?: string
}

export type OnetRatingCategory = {
  _id: string
  _type: 'onetRatingCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  categoryDomain?: 'education' | 'trainingExperience' | 'workContext' | 'task'
  element?: OnetContentModelElementReference
  scale?: OnetScaleReference
  category?: number
  categoryDescription?: string
}

export type OnetJobZone = {
  _id: string
  _type: 'onetJobZone'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  jobZone?: number
  name?: string
  experience?: string
  education?: string
  jobTraining?: string
  examples?: string
  svpRange?: string
}

export type OnetScale = {
  _id: string
  _type: 'onetScale'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  scaleId?: string
  scaleName?: string
  minimum?: number
  maximum?: number
}

export type OnetContentModelElement = {
  _id: string
  _type: 'onetContentModelElement'
  _createdAt: string
  _updatedAt: string
  _rev: string
  importKey?: string
  elementId?: string
  elementName?: string
  description?: string
  parentElement?: OnetContentModelElementReference
  relatedWorkActivities?: Array<
    {
      _key: string
    } & OnetContentModelElementReference
  >
  relatedWorkContext?: Array<
    {
      _key: string
    } & OnetContentModelElementReference
  >
  surveyItems?: Array<
    {
      _key: string
    } & OnetSurveyItem
  >
}

export type SanityAgentContext = {
  _id: string
  _type: 'sanity.agentContext'
  _createdAt: string
  _updatedAt: string
  _rev: string
  version?: string
  name?: string
  slug?: Slug
  groqFilter?: string
  instructions?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | WorkflowDefinition
  | Slug
  | WorkflowAssignment
  | WorkflowOffRamp
  | WorkflowLucideIcon
  | WorkflowStage
  | WorkflowColor
  | WorkflowTaskTemplate
  | WorkflowRole
  | WorkflowSetStatus
  | RgbaColor
  | HsvaColor
  | HslaColor
  | WorkflowUser
  | CoachingGuide
  | OnetOccupationMetadataItem
  | OnetInterestReference
  | OnetInterestAreaScore
  | OnetOccupationReference
  | OnetRelatedOccupationItem
  | OnetContentModelElementReference
  | OnetScaleReference
  | OnetRatingCategoryReference
  | OnetRatingItem
  | OnetWorkStyleItem
  | OnetSoftwareSkillItem
  | OnetReportedTitleItem
  | OnetJobTitleItem
  | OnetEmergingTaskItem
  | OnetTaskDwaItem
  | OnetTaskRatingItem
  | OnetTaskItem
  | OnetJobZoneReference
  | OnetOccupation
  | OnetSurveyItem
  | OnetInterest
  | OnetLevelScaleAnchor
  | OnetRatingCategory
  | OnetJobZone
  | OnetScale
  | OnetContentModelElement
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/src/pages/api/career-quizzes.ts
// Variable: CAREER_QUIZZES_QUERY
// Query: *[_type == "careerQuiz" && !(_id in path("drafts.**"))] | order(coalesce(listOrder, 1000000) asc, name asc) { _id, name, provider, url, description, focus, cost }
export type CAREER_QUIZZES_QUERY_RESULT = Array<never>

// Source: ../web/src/pages/api/saved-occupations.ts
// Variable: SAVED_OCCUPATIONS_QUERY
// Query: *[_type == "onetOccupation" && onetsocCode in $codes]{		"code": onetsocCode,		title,		description,		"jobZone": jobZone->{"level": jobZone, name},		"interests": interestProfile.highPoints,		"education": ratings[domain == "education" && scale->scaleId in ["RL", "RQ"] && dataValue > 0]			| order(dataValue desc){"scale": scale->scaleId, "category": ratingCategory->categoryDescription, "percent": dataValue},		"topSkills": ratings[domain in ["essentialSkills", "transferableSkills"] && scale->scaleId == "IM"]			| order(dataValue desc)[0...3].element->elementName	}
export type SAVED_OCCUPATIONS_QUERY_RESULT = Array<{
  code: string | null
  title: string | null
  description: string | null
  jobZone: {
    level: number | null
    name: string | null
  } | null
  interests: Array<string> | null
  education: Array<{
    scale: string | null
    category: string | null
    percent: number | null
  }> | null
  topSkills: Array<string | null> | null
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "careerQuiz" && !(_id in path("drafts.**"))] | order(coalesce(listOrder, 1000000) asc, name asc) { _id, name, provider, url, description, focus, cost }': CAREER_QUIZZES_QUERY_RESULT
    '*[_type == "onetOccupation" && onetsocCode in $codes]{\n\t\t"code": onetsocCode,\n\t\ttitle,\n\t\tdescription,\n\t\t"jobZone": jobZone->{"level": jobZone, name},\n\t\t"interests": interestProfile.highPoints,\n\t\t"education": ratings[domain == "education" && scale->scaleId in ["RL", "RQ"] && dataValue > 0]\n\t\t\t| order(dataValue desc){"scale": scale->scaleId, "category": ratingCategory->categoryDescription, "percent": dataValue},\n\t\t"topSkills": ratings[domain in ["essentialSkills", "transferableSkills"] && scale->scaleId == "IM"]\n\t\t\t| order(dataValue desc)[0...3].element->elementName\n\t}': SAVED_OCCUPATIONS_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
